# Generated by Django 5.2.5 on 2025-11-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
